/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebBox {
        "variant"?: "primary" | "secondary" | "tertiary";
    }
    interface WebButton {
        "options"?: "outline";
        "variant"?: "primary" | "secondary" | "tertiary";
    }
    interface WebMfe {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebBoxElement extends Components.WebBox, HTMLStencilElement {
    }
    var HTMLWebBoxElement: {
        prototype: HTMLWebBoxElement;
        new (): HTMLWebBoxElement;
    };
    interface HTMLWebButtonElement extends Components.WebButton, HTMLStencilElement {
    }
    var HTMLWebButtonElement: {
        prototype: HTMLWebButtonElement;
        new (): HTMLWebButtonElement;
    };
    interface HTMLWebMfeElement extends Components.WebMfe, HTMLStencilElement {
    }
    var HTMLWebMfeElement: {
        prototype: HTMLWebMfeElement;
        new (): HTMLWebMfeElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "web-box": HTMLWebBoxElement;
        "web-button": HTMLWebButtonElement;
        "web-mfe": HTMLWebMfeElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebBox {
        "variant"?: "primary" | "secondary" | "tertiary";
    }
    interface WebButton {
        "options"?: "outline";
        "variant"?: "primary" | "secondary" | "tertiary";
    }
    interface WebMfe {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "web-box": WebBox;
        "web-button": WebButton;
        "web-mfe": WebMfe;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-box": LocalJSX.WebBox & JSXBase.HTMLAttributes<HTMLWebBoxElement>;
            "web-button": LocalJSX.WebButton & JSXBase.HTMLAttributes<HTMLWebButtonElement>;
            "web-mfe": LocalJSX.WebMfe & JSXBase.HTMLAttributes<HTMLWebMfeElement>;
        }
    }
}
